### PR TITLE
upgrade jsonnet to v0.9.5

### LINKED ISSUE #15: Update to jsonnet 0.9.0
Any plans to update to jsonnet 0.9.0?

### PR DESCRIPTION
**Pull request by guoshimin**
fixes #15 

TODO:
- [ ] someone needs to upload the v0.9.5 tarball to the bazel mirror

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by nictuku** [comment]
Any updates on this? Without this change we can't current ksonnet libs:

```
$ bazel build //bababot:bababot_serverkube_dev_deployment_json
INFO: Found 1 target...
ERROR: /Users/yves/src/github.com/nictuku/microclusters/bababot/BUILD.bazel:19:1: error executing shell command: 'set -e; bazel-out/host/bin/external/jsonnet/cmd/jsonnet -J . rules/deployment.jsonnet -o bazel-out/darwin_x86_64-fastbuild/bin/bababot/bababot_serverkube_dev_deployment.json' failed (Exit 1).
STATIC ERROR: ./external/com_github_ksonnet_lib/ksonnet.beta.2/k8s.libsonnet:311:50: Not a binary operator: =
Target //bababot:bababot_serverkube_dev_deployment_json failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.234s, Critical Path: 2.82s
```

The offending section being:

```
      // Deployment enables declarative updates for Pods and ReplicaSets.
      deployment:: {
        local kind = {kind: "Deployment"},
        new(name, replicas, containers, podLabels={app: name}):: apiVersion + kind + self.mixin.metadata.withName(name) + self.mixin.spec.withReplicas(replicas) + self.mixin.spec.template.spec.withContainers(containers) + self.mixin.spec.template.metadata.withLabels(podLabels),

```

Where the error is at `podLabels={`.

I've verified that it works after an upgrade to 0.9.5

**Comment by mattmoor** [comment]
@damienmg Ping

**Comment by ashi009** [comment]
Any reason for mirroring this tarball on bazel.build? IMHO, Github's 99.95% uptime SLA for github.com/google is good enough. 

Drop the mirror url will make this file a pure GitHub.com managed file without having to wait for a Google internal approval.

**Comment by davidstanke** [comment]
One nit: can you change http://mirror.bazel.build/[...] --> **https**://mirror.bazel.build/[...]? We're now serving all *.bazel.build domains with SSL.

**Comment by guoshimin** [comment]
Done

**Comment by guoshimin** [comment]
Ping

**Comment by guoshimin** [comment]
Ping

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ashi009** [comment]
@guoshimin Please drop `https://mirror.bazel.build/github.com/google/jsonnet/archive/v0.9.5.tar.gz`.  This change involves an google internal change list, which may take days to complete.  So as I suggested before, I believe dropping it is a fair choice. 

@davidstanke Please merge this. This 4-line PR has been opened for months, I don't see any reason to hold it back.

**Comment by guoshimin** [comment]
I'm happy to drop it, but it's the Bazel teams call.

**Comment by davidstanke** [comment]
Apologies for the delay and thanks for the ping(s). Merging!

**Comment by guoshimin** [comment]
@davidstanke Can you also approve https://github.com/bazelbuild/rules_jsonnet/pull/35? Thanks!

**Pull request merged**
