### PR TITLE
Add github workflows to make releases when a tag is pushed.

### PR DESCRIPTION
**Pull request by chrismgrayftsinc**

### CODE REVIEW

**Comment by chrismgrayftsinc** [comment]
These workflows are taken from https://github.com/bazel-contrib/rules-template

**Comment by chrismgrayftsinc** [comment]
This is not working yet

**Comment by EdSchouten** [comment]
A similar change has been made in #187. Thanks for your contribution!

**Comment by chrismgrayftsinc** [comment]
> A similar change has been made in #187. Thanks for your contribution!

Thanks for getting it past the finish line!

**Pull request closed without merging**
