### PR TITLE
Update README.md

### LINKED ISSUE #24: Wrong Readme in 0.0.3
Now there is:
```
http_archive(
    name = "io_bazel_rules_jsonnet",
    urls = [
        "http://mirror.bazel.build/github.com/bazelbuild/rules_jsonnet/archive/0.0.2.tar.gz",
        "https://github.com/bazelbuild/rules_jsonnet/archive/0.0.2.tar.gz",
    ],
    sha256 = "5f788c7719a02ed2483641365f194e9e5340fbe54963d6d6caa09f91454d38b8",
    strip_prefix = "rules_jsonnet-0.0.2",
)
load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_repositories")

jsonnet_repositories()
```

And it should be:
```
http_archive(
    name = "io_bazel_rules_jsonnet",
    urls = [
        "http://mirror.bazel.build/github.com/bazelbuild/rules_jsonnet/archive/0.0.3.tar.gz",
        "https://github.com/bazelbuild/rules_jsonnet/archive/0.0.3.tar.gz",
    ],
    sha256 = "e0f42a31f5b2feeeb5496d40cb0b7c5d3872bd7e0bdb44b04543cce96de321f8",
    strip_prefix = "rules_jsonnet-0.0.3",
)
load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_repositories")

jsonnet_repositories()
```

### PR DESCRIPTION
**Pull request by sparkprime**
Fix #24

### CODE REVIEW

**Comment by mariusgrigoriu** [comment]
But the sha was not updated

**Comment by sparkprime** [comment]
True.  How do I test it?  Can you update it and send a PR

**Comment by sparkprime** [comment]
just run sha256 on the tarball?  that would be e0f42a31f5b2feeeb5496d40cb0b7c5d3872bd7e0bdb44b04543cce96de321f8

**Comment by mariusgrigoriu** [comment]
I think so. I since moved on to use the latest commit because there are some key differences between that and the release so my WORKSPACE no longer has the correct sha. Perhaps the README can be generated?

**Pull request merged**
