### PR TITLE
Upgrade go-jsonnet to v0.17.0

### PR DESCRIPTION
**Pull request by paiyar**
Background
---
Upgrade go-jsonnet from v0.15.0 to v0.17.0

### CODE REVIEW

**Comment by paiyar** [comment]
@googlebot I signed it!

**Comment by paiyar** [comment]
@googlebot I consent.

**Comment by paiyar** [comment]
/cc @Globegitter 
/cc @sparkprime 

Could I trouble you to manually set the cla label to yes and review?

**Comment by Globegitter** [comment]
@paiyar all looking good - thanks for the update.

**Pull request merged**
