### PR TITLE
Add extra_args to allow passing more arguments to jsonnet.

### LINKED ISSUE #104: Support for the "--string" flag
My jsonnet config needs the "--string" flag to ouput straight yaml instead of quoted strings. I could not find support for this flag, or to passing `extra_args` to the jsonnet build commnd. Does that exist?

### PR DESCRIPTION
**Pull request by jarondl**
Allow users to pass, for example:

    extra_args=["--string"],

Fix #104

### CODE REVIEW

**Comment by Globegitter** [comment]
I was on holiday the past week, will try to look at it the next couple of days or latest beginning of next week.

**Comment by Globegitter** [comment]
Could you add a test for this also please.

**Comment by jarondl** [comment]
> Could you add a test for this also please @jarondl.

Added a test, including a new parameter to not canonicalize the golden file.

**Comment by jdelfino** [comment]
We'd also like to use this - would you mind taking another look @Globegitter? Thanks!

**Comment by Globegitter** [comment]
Thanks for the addition.

**Pull request merged**
