### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding global CODEOWNERS based on registered collaborators

### CODE REVIEW

**Comment by Globegitter** [comment]
I am not sure if @davidzchen is still really active on this project but not sure how that is handled in general so would still be happy to accept if you want.

**Comment by dslomov** [comment]
Let's not add people who are no longer active - we can always add them back later - ptal

**Comment by dslomov** [comment]
Also @davidzchen was the only admin of this repository - anyone of you @Globegitter @sparkprime want to be an admin?

**Comment by Globegitter** [comment]
@dslomov happy to be an admin.

**Pull request merged**
